### PR TITLE
Logo and Branding Design Done

### PR DESCRIPTION
**Pull request by Kuldeepagrahari**
image
this is the logo , I have created and added to navbar according to application's services and moto, Hopefully you like it!

### CODE REVIEW

**Comment by Shivg2901** [comment]
@Kuldeepagrahari 
The logo is good 
But you're supposed to come up with a brand name too

**Comment by Kuldeepagrahari** [comment]
Brandname is Zapier right?

**Comment by Shivg2901** [comment]
@Kuldeepagrahari yes
I dont want the project to be named after the original thing

**Comment by Shivg2901** [comment]
@Kuldeepagrahari Good work

**Pull request merged**
